// <auto-generated />
using System;
using DataAccess.MsSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211109210604_v5")]
    partial class v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2004, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Vlad",
                            Phone = "0500653293",
                            Salary = 500.23m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2008, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Xenia",
                            Phone = "0669925380",
                            Salary = 499.23m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2021, 11, 9, 23, 6, 4, 69, DateTimeKind.Local).AddTicks(3450),
                            Married = true,
                            Name = "Ivan",
                            Phone = "0523673293",
                            Salary = 12.23m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
